-- MySQL Script generated by MySQL Workbench
-- Fri Jan 18 05:02:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

DROP DATABASE IF EXISTS `mydb`;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `time_zone` VARCHAR(45) NULL,
  PRIMARY KEY (`email`));


-- -----------------------------------------------------
-- Table `mydb`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manager` (
  `user_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_email`),
  CONSTRAINT `fk_manager_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `user_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_email`),
  CONSTRAINT `fk_admin_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teamlead`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teamlead` (
  `user_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_email`),
  CONSTRAINT `fk_teamlead_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`team` (
  `name` INT NOT NULL,
  `teamlead_user_email` VARCHAR(255) NOT NULL,
  `max_swes_out` INT NULL,
  PRIMARY KEY (`name`, `teamlead_user_email`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_team_teamlead1_idx` (`teamlead_user_email` ASC),
  CONSTRAINT `fk_team_teamlead1`
    FOREIGN KEY (`teamlead_user_email`)
    REFERENCES `mydb`.`teamlead` (`user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`swe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`swe` (
  `user_email` VARCHAR(255) NOT NULL,
  `team_name` INT NOT NULL,
  `teamlead_user_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_email`),
  INDEX `fk_swe_user1_idx` (`user_email` ASC),
  INDEX `fk_swe_team1_idx` (`team_name` ASC, `teamlead_user_email` ASC),
  CONSTRAINT `fk_swe_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_swe_team1`
    FOREIGN KEY (`team_name` , `teamlead_user_email`)
    REFERENCES `mydb`.`team` (`name` , `teamlead_user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`request` (
  `request_id` INT NOT NULL AUTO_INCREMENT,
  `request_create_time` TIMESTAMP NOT NULL,
  `swe_user_email` VARCHAR(255) NOT NULL,
  `teamlead_user_email` VARCHAR(255) NOT NULL,
  `team_name` INT NOT NULL,
  PRIMARY KEY (`request_id`, `swe_user_email`, `teamlead_user_email`, `team_name`),
  INDEX `fk_Request_swe1_idx` (`swe_user_email` ASC),
  INDEX `fk_Request_teamlead1_idx` (`teamlead_user_email` ASC),
  INDEX `fk_request_team1_idx` (`team_name` ASC),
  CONSTRAINT `fk_Request_swe1`
    FOREIGN KEY (`swe_user_email`)
    REFERENCES `mydb`.`swe` (`user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_teamlead1`
    FOREIGN KEY (`teamlead_user_email`)
    REFERENCES `mydb`.`teamlead` (`user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_team1`
    FOREIGN KEY (`team_name`)
    REFERENCES `mydb`.`team` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`events` (
  `swe_email` VARCHAR(255) NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `event_created` DATETIME NOT NULL,
  `teamlead_user_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`teamlead_user_email`, `event_created`),
  INDEX `fk_events_swe1_idx` (`swe_email` ASC),
  CONSTRAINT `fk_events_teamlead1`
    FOREIGN KEY (`teamlead_user_email`)
    REFERENCES `mydb`.`teamlead` (`user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_swe1`
    FOREIGN KEY (`swe_email`)
    REFERENCES `mydb`.`swe` (`user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
