# Generated by Django 2.1.5 on 2019-01-25 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.contrib.auth import models as authmodels

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_app', '0002_auto_20190122_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swe',
            name='user_email',
        ),
        migrations.AddField(
            model_name='swe',
            name='user_id',
            field=models.OneToOneField( on_delete=django.db.models.deletion.CASCADE,
                                       primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
