# Generated by Django 2.1.5 on 2019-01-25 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0009_request_swe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='swe_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='s_app.Swe'),
        ),
    ]
