# Generated by Django 2.1.5 on 2019-01-29 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('s_app', '0010_auto_20190125_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swe',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='swe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='s_app.Swe', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='request',
            name='swe_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='s_app.Swe', to_field='user_id'),
        ),
    ]
