# Generated by Django 2.1.5 on 2019-01-30 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0011_auto_20190128_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='swe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='s_app.Swe'),
        ),
        migrations.AlterField(
            model_name='request',
            name='swe_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='s_app.Swe'),
        ),
    ]
