# Generated by Django 2.1.5 on 2019-01-30 04:26

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0012_auto_20190129_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='swe',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='US/Eastern'),
        ),
    ]
