# Generated by Django 2.1.5 on 2019-02-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0013_swe_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time']},
        ),
    ]
