# Generated by Django 2.1.5 on 2019-02-21 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0014_auto_20190201_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamlead',
            old_name='user_email',
            new_name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='startegic_products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='s_app.Teamlead', to_field='user_email'),
        ),
    ]
